### ISSUE TITLE
Css личный кабинет

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#1]
![3](https://cloud.githubusercontent.com/assets/16444512/12006586/c9ec7adc-abf5-11e5-9606-0c55908cf5cf.jpg)
![1](https://cloud.githubusercontent.com/assets/16444512/12006587/c9ed7266-abf5-11e5-8329-bdea9fedb004.jpg)

**Comment by AngryGantz** [comment]
Исправлено. Если ок, закрывайте запрос.
