### ISSUE TITLE
"Не срочно" редактирование комментов

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#10]
Я пользователь я могу отредактировать свои комменты (Хотелось бы)

**Comment by AngryGantz** [comment]
хм...  не уверен... Это плохая практика, говорю как человек который модерировал множество форумов (комменты это минифорум по сути)

**Comment by ooduhastoo** [comment]
я создал сообщение у меня мало времени забыл перевести шрифт ) Повис коммент кракозябры  пока модератор не исправит .. Не знаю как быть

**Comment by AngryGantz** [comment]
никак. Написать другой коммент, этот модер потрет с кракозябрами. Нельзя давать удалять или редактировать  комменты. Это холиварная тема. Если настаиваете сделаю, но это очень плохая практика.

**Comment by ooduhastoo** [comment]
ок отбой тогда
