### ISSUE TITLE
Стекло Logo

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#101]
дайте возможность менять лого. Надо стекло проект поменять

**Comment by ooduhastoo** [comment]
![logo2](https://cloud.githubusercontent.com/assets/16444512/13113423/6edb17fc-d5a8-11e5-855d-b9ce5dea8290.png)

**Comment by AngryGantz** [comment]
Fixed. Чуть позже сделаю в админке.
