### ISSUE TITLE
"Не срочно" урл материала

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#11]
Урл в себя должен включать название рецепта Id не надо  http://42607.simplecloud.club/recipie/sup_kandey

**Comment by AngryGantz** [comment]
Сделано. Предусмотрена возможность дублирования slug-поля (не влияет на результат выдачи, так как реально выдача идет по id а не по slug). Так что за этот аспект мона не волноваться -). В новых рецептах генерируется автоматически при сохранении из заголовка рецепта (в админке если оставить поле пустым, тоже)
