### ISSUE TITLE
"Не срочно" Печать материала

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#13]
Печать одного рецепта занимает 3 листа 
Должна в себя включать : 
Название рецепта
Время приготовления
Описание ?
Игридиенты
Шаги
![11](https://cloud.githubusercontent.com/assets/16444512/12006845/423104ee-ac01-11e5-90fa-56cd980bbde8.jpg)

**Comment by AngryGantz** [comment]
Что-то ещё надо? Или закрыт вопрос?

**Comment by ooduhastoo** [comment]
Компактнее не получится с шаблоном для печати ?

**Comment by AngryGantz** [comment]
ну там только ингридиенты если только попробовать "копактизировать" для печати. А еще что? Там и так только текст и картинки остается...

**Comment by AngryGantz** [comment]
Кстати, понажимайте Ctrl F5. Комментов быть не должно.

**Comment by ooduhastoo** [comment]
Честно говоря на печати убожество получается )))  какието нолики ... Текст шага падает под картинку )))
![111111111111111111111111111](https://cloud.githubusercontent.com/assets/16444512/12011064/1906f17c-acd9-11e5-8804-b2b6dfd84f9d.jpg)

**Comment by AngryGantz** [comment]
Надо верстать отдельный шаблон под печать.... Пусть повисит чуток. Я сделаю... позже...

**Comment by AngryGantz** [comment]
Сделано

**Comment by AngryGantz** [comment]
Ctrl-F5 долго нажимать...

**Comment by ooduhastoo** [comment]
сутки ?)

**Comment by AngryGantz** [comment]
ну не сутки, но я раз 10 жал пока сработало...
