### ISSUE TITLE
"не срочно" Невозможно выйти из печати рецепта

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#14]
Нажал на кнопку печати рецепты,передумал печатать обратно стрелками на сайт не выйти и продолжается постоянная загрузка . Даже при стирании части урл все равно открывается страница печати 
![12](https://cloud.githubusercontent.com/assets/16444512/12006856/ed77f5c4-ac01-11e5-98b4-b2e9a30fe939.jpg)

**Comment by AngryGantz** [comment]
Вроде как этот вопрос решен?
