### ISSUE TITLE
"Важно" Капча при регистрации 

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#16]
А то роботы нарегятся 
![16](https://cloud.githubusercontent.com/assets/16444512/12006895/b49a80ee-ac03-11e5-9cc4-8f32d2100ffe.jpg)

**Comment by AngryGantz** [comment]
Поставил. Устроит такой вариант?  Это чтоб без фанатизма и мата юзеров ...  Считаю менять только если будут проблемы... Но решать вам
