### ISSUE TITLE
"Не срочно"  slug не работает

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#26]
Мета данные пустые у материала... А в админке он генерирует на англ 
![1111111111111111](https://cloud.githubusercontent.com/assets/16444512/12008110/cb3a8e34-ac3f-11e5-826a-023e03cc7255.jpg)
![3333333333333333333](https://cloud.githubusercontent.com/assets/16444512/12008111/cb3b7678-ac3f-11e5-9077-adafdc9d0215.jpg)

**Comment by AngryGantz** [comment]
А при чем тут Slug и метаданные? И естественно Slug на английском...
