### ISSUE TITLE
"Не срочно" кнопки поделиться в соц сетях не активны

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#27]
В рецептах кнопки поделиться в соц сетях не активны

**Comment by AngryGantz** [comment]
Так что делаем? Ставим черный блок или копаем как прицепить к своим кнопкам? Или ставим черный блок, вопрос не закрываем а откладываем?

**Comment by ooduhastoo** [comment]
Вставьте то что дал и все

**Comment by AngryGantz** [comment]
Вставил
