### ISSUE TITLE
"Важно" Доработка админки "Маркеры"

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#3]
Было бы очень удобно если было бы видно к какой группе принадлежат маркеры. Что бы не запутаться когда их будет много
![4](https://cloud.githubusercontent.com/assets/16444512/12006620/457501e6-abf7-11e5-86e7-828c0c26d76c.jpg)

**Comment by AngryGantz** [comment]
Сделано. Если норм, закрывайте.

**Comment by ooduhastoo** [comment]
не вижу выполнения
