### ISSUE TITLE
"Нет фото"  картинка

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#30]
Картинка для нет фото .. Может конечно будет лучше пнг смотреться 
![no-photo](https://cloud.githubusercontent.com/assets/16444512/12008236/394bd462-ac47-11e5-8f3f-d7d4781db3bf.png)

**Comment by ooduhastoo** [comment]
![0000000000000](https://cloud.githubusercontent.com/assets/16444512/12015621/912f525a-ad58-11e5-97a4-abcc2721a38d.jpg)

**Comment by AngryGantz** [comment]
сделано
