### ISSUE TITLE
"Не срочно" Изменить аватар

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#31]
Хотелось бы при наведении на иконку менялся курсор. Нажимаю на иконку открывается обзор файлов на компьютере закрываю обзор он опять открывается ...  Не косяк но он пытается 2 раза открыться)
![xxxxxxxxxxxxxx](https://cloud.githubusercontent.com/assets/16444512/12008310/ce8698e2-ac4b-11e5-950d-dfbfee65ec68.jpg)

**Comment by ooduhastoo** [comment]
И фото грузиться со второго раза

**Comment by AngryGantz** [comment]
Так, половина сделана, насчет второй попытки. По курсору посмотрю
