### ISSUE TITLE
"Не срочно" Группировка маркеров

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#33]
С маркерами не очень удобно работать  так как при нажатии на стрелку группировки происходит группировка маркеров по алфавиту .. Хотелось бы что бы наживая на стрелку происходила группировка по группам 
![5555555555555555555555](https://cloud.githubusercontent.com/assets/16444512/12009939/0a3731dc-aca9-11e5-8468-b0112e1b0572.jpg)

**Comment by AngryGantz** [comment]
Так жмите на сортировку по группам а не на сортировку по названиям....  (на данном скриншоте это справа от заглоловка "Входит в группы", бледная двойная стрелка)
