### ISSUE TITLE
"Не срочно" картинка маркера

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#35]
Куда выводится картинка маркера ?? Если она как для категории то нет окошка для текста описания маркера (категории) ...   Еще хорошо бы что бы была форма alt="" картинки  и совсем бы замечательно если эта форма не заполнена прописывалось название картинки (Это для всех картинок на сайте, полезно для продвижения)
![kkkkkkkkkkkkkkkkkkk](https://cloud.githubusercontent.com/assets/16444512/12009984/b69623a0-acab-11e5-9993-4c349d8eddd8.jpg)

**Comment by AngryGantz** [comment]
Картинка маркера сейчас выводится только в 1 месте - боковом правом меню. Куда еще надо - заказывайте. Альты сделаю.
