### ISSUE TITLE
"Не срочно" Логин капча защита

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#37]
Вход на сайт капча и желательно после неправильного ввода логина и пасса блок на 15 мин
![33333333333333333333333333333333333333333333333333](https://cloud.githubusercontent.com/assets/16444512/12010071/a8031c72-acaf-11e5-9d12-96d0c4f5365b.jpg)

**Comment by AngryGantz** [comment]
Вы хотите чтобы на ваш сайт кроме роботов никто не ходил? Как скажете. Сделаю. Только тогда на кой мы там дизайн делали, формы добавлений и прочее? Роботом это не надо, а людей не будет...

**Comment by AngryGantz** [comment]
P.S. Блокировать по какому принципу? В куках или по айпи? Вдруг кто-то шибко упорный захочет все-таки зайти на сайт и откроет другой браузер?

P.P.S Вы лично сколько раз в этой жизни встречались с попыткой в лоб зайти на сайт как зарегистрированный пользователь, не являясь таковым, методом перебора логинов и паролей в форме?

**Comment by ooduhastoo** [comment]
ок  но капча нужна

**Comment by AngryGantz** [comment]
Капча да, тут я согласная -))

**Comment by ooduhastoo** [comment]
Поставите ?

**Comment by AngryGantz** [comment]
Сделано
