### ISSUE TITLE
"Важно" Добавление рецепта

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#38]
Важные маркеры которые будут выводится потом в правом меню
![pppp](https://cloud.githubusercontent.com/assets/16444512/12010093/c92e2d5a-acb0-11e5-9d97-753ba15742d0.jpg)

**Comment by AngryGantz** [comment]
Это отдельные маркеры, не группы?

**Comment by ooduhastoo** [comment]
Отдельные

**Comment by AngryGantz** [comment]
Сделано. Реализован новый механизм внедрения маркеров. У маркеров появилось новое поле, в админке показано как чекбокс "показать в форме добавления поста". Если взвести, маркер будет добавлен в форму. Количество неограничено.
