### ISSUE TITLE
"Не срочно" Блог малевича

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#39]
![iiiiiiiiiiiiiiiiiiiii](https://cloud.githubusercontent.com/assets/16444512/12010101/06e2e28a-acb1-11e5-8e1e-6f08a93a0a77.jpg)

**Comment by AngryGantz** [comment]
Если речь про наличие иконки на квадрате, то сделано. Если что-то еще, разжуйте.

**Comment by ooduhastoo** [comment]
как везде надо сделать)
