### ISSUE TITLE
"Не срочно" Комментарии к материалу

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#4]
Капча фильтр слов и ссылок
зарегистрированные  и не зарегистрированные
могут: оставлять комментарии  после ввода капчи
не могут: давать ссылки и печатать матом

Не зарегистрированные  пользователи видят форму где надо указать Имя емаил .. Коммент не зарегистрированного пользователя имеет картинку noAvatar
![5](https://cloud.githubusercontent.com/assets/16444512/12006679/056d06c2-abfa-11e5-9750-d894443645fb.jpg)

**Comment by AngryGantz** [comment]
Что выводить в заголовке комментария от гостя?

**Comment by ooduhastoo** [comment]
Гость
