### ISSUE TITLE
"Не срочно" Счетчики

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#42]
life

<script type="text/javascript"></script>

Метрика без картинки

<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter34442430 = new Ya.Metrika({
                    id:34442430,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>

<noscript><div><img src="https://mc.yandex.ru/watch/34442430" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

**Comment by AngryGantz** [comment]
сделаю блок под футером, втащу в админку, сами будете туда запихивать что душе угодно

**Comment by AngryGantz** [comment]
Создайте новый рекламный блок, место посадки выбрать из списка - foot_script.  Включить блок, включить показ содержимого (заголовок и картинку не включать) В содержимое воткнуть что душе угодно.

**Comment by ooduhastoo** [comment]
Не выводит счетчики

**Comment by AngryGantz** [comment]
Исправлено
