### ISSUE TITLE
"Не срочно" Фильтры под слайдером

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#43]
![0000000000000000000000000](https://cloud.githubusercontent.com/assets/16444512/12010298/dc9450d2-acb9-11e5-9ecb-b52031d91bfc.jpg)

**Comment by AngryGantz** [comment]
Не понял. Что значит "Маркер-ингридиенты". У нас ингридиенты - равтекст в обычном поле.
По популярности. В каком месте это можно сделать фильтром? Дайте критерии отбора в фильтр.

**Comment by ooduhastoo** [comment]
1Фильтр  Название "Ингридиенты"    Варианты : Блюда из мяса блюда из птицы и тп   из группы маркеров ингридиенты..
2 фильтр   Искать рецепты по популярности или просмотрам или комментариям (Комментарий много )   Соответственно выдавать по убыванию

**Comment by AngryGantz** [comment]
1. Дошло.
2. То есть вы в фильтры засовываете не фильтр, а порядок соритровки, так чтоли? Давайте фильтрам всё таки  оставим фильтрово...  Там всю логику обработки тогда менять...   Ну или пусть пока висит открытым тикет...

**Comment by ooduhastoo** [comment]
Тогда 1 фильтр добавьте а 5 под вопросом пока

**Comment by AngryGantz** [comment]
добавил Основные ингридиенты. Вернее заменил кухню на них. Надо было добавить?

**Comment by ooduhastoo** [comment]
добавить ..

**Comment by ooduhastoo** [comment]
И закрою тогда заявку

**Comment by AngryGantz** [comment]
Сделано
