### ISSUE TITLE
"Не срочно" Правое меню

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#44]
Маркеры : 
Детская кухня
Мультиварка
Диетическая кухня
Постная кухня

Картинки я предоставлю

**Comment by AngryGantz** [comment]
Создайте группу "Правое меню 1" и воткните туда те маркеры, которые нужны. Я воткну.
Картинки предоставлять мне не надо. Воткните их в нужные маркеры через админку.

**Comment by ooduhastoo** [comment]
Нельзя так сделать ) группа маркеров упадет формой в добавление рецепта)))

**Comment by AngryGantz** [comment]
Я это исправлю как руки дойдут. В пределах 2 суток думаю

**Comment by AngryGantz** [comment]
В группы маркеров добавлен функционал, аналогичный "свободным" маркерам - выбор в админке какие группы светить в формке добавления рецепта. Можно собирать боковые  меню, спец группы  для фильтров, главного меню  и прочее.

**Comment by ooduhastoo** [comment]
Спасибо

**Comment by ooduhastoo** [comment]
В правое меню группу маркеров id7 очередность  маркеров такая же как в админке

**Comment by AngryGantz** [comment]
Добавлено новое поле к маркерам "порядок сортировки" и соответствующий механизм вывода правого меню. Просто ставьте порядковые номера в это поле.  Не то что-бы безумно удобно,  но по другому не придумал. Это ведь не частая операция, думаю можно и так...
