### ISSUE TITLE
"Не срочно" Маркер напитки и выпечка

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#45]
К маркеру напитки не подходят фильтры и получается не логично .... Добавить группу напитки и выпечка в верхнее меню .. Они будут делиться на алкогольные безалкогольные . Тоже самое с выпечкой

**Comment by AngryGantz** [comment]
делайте нужные группы и скажете какие группы добавить. Если маркера без групп, то написать какие. Пример заявки:

Меню: 
1 позиция - Группа  Выпечка, id=6
2 позиция - Группа кухня, id = 1
3 позиция - Маркер "Булочки"

Вот примерно так. А то нифига не понял чего и куда.

**Comment by ooduhastoo** [comment]
Меню 4 позиция : id 6  5 позиция : id 5

**Comment by AngryGantz** [comment]
угу
