### ISSUE TITLE
"Важно" Настройка почтового сервера

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#46]
Настройка почтового сервера  и отправленных пользователю сообщений... 
Текст сообщений с html кодом я предоставлю для всех вариантов отправленных сообщений
настройка перенаправленний важных сообщений на личную почту

**Comment by AngryGantz** [comment]
"настройка перенаправленний важных сообщений на личную почту" разжевать.
Ну и html писем собственно где? А то срочно... срочно....  Приложить в архиве.

**Comment by ooduhastoo** [comment]
Я отправил вам письмо спасибо за регистрацию.. Получиться код скопировать?

**Comment by AngryGantz** [comment]
ЗАвернуть файл в архив и отправить.

**Comment by ooduhastoo** [comment]
Отправил "Спасибо за регистрацию"

**Comment by ooduhastoo** [comment]
Только надо в код вставить ссылку на активацию аккаунта

**Comment by AngryGantz** [comment]
Тэкс. активационное письмо ваше поставлено, проверено. Оповещения о регистрации и подписке на новости приходят на адрес, указанный в соответствующем параметре настроек CMS

**Comment by ooduhastoo** [comment]
3 картинка  не отображается где то я накосячил...  Сделаю остальные письма вам скину тогда и закрою заявку
![1234](https://cloud.githubusercontent.com/assets/16444512/12015521/0cf250ce-ad57-11e5-8f9a-62437bb967f2.jpg)

**Comment by AngryGantz** [comment]
Подправил 3ю картинку

**Comment by ooduhastoo** [comment]
Спасибо. Остальные письма сделаю скину

**Comment by ooduhastoo** [comment]
Отправлено письмо на почту.  В прикрепленном html " Письмо восстановления пароля"

**Comment by AngryGantz** [comment]
Сделано

**Comment by ooduhastoo** [comment]
я подписался на новости .. Добавил новость оповещение мне так и не пришло на почту ... Делать шаблон письма ?

**Comment by ooduhastoo** [comment]
Письмо восстановления пароля проверил работает спасибо

**Comment by AngryGantz** [comment]
Закрываем тикет или еще что-то?
