### ISSUE TITLE
"Важно" Лого для админки

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#48]
=)))
![logo1](https://cloud.githubusercontent.com/assets/16444512/12011322/2cdb97c6-ace2-11e5-92e6-d4d39c74e6a4.jpg)
![logo admin](https://cloud.githubusercontent.com/assets/16444512/12011323/2cdf5834-ace2-11e5-94e0-4ecce2c2f873.jpg)

**Comment by AngryGantz** [comment]
=))) Не предусмотрено =))))
