### ISSUE TITLE
"ВАЖНО ОШИБКА" Ошибка при добавлении рецепта

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#49]
Ошибка при добавлении рецепта . Не знаю в чем дело (

**Comment by ooduhastoo** [comment]
Шагов 8 наверно 
![chicken-fajitas-2](https://cloud.githubusercontent.com/assets/16444512/12011652/6d532874-acf0-11e5-9bd3-4457ff562e92.jpg)
![chicken-fajitas-6](https://cloud.githubusercontent.com/assets/16444512/12011657/6d553b78-acf0-11e5-869d-cc01ec53e8d8.jpg)
![chicken-fajitas-640-dm](https://cloud.githubusercontent.com/assets/16444512/12011653/6d5387e2-acf0-11e5-85f4-463a5e31a524.jpg)
![chicken-fajitas-a-2](https://cloud.githubusercontent.com/assets/16444512/12011655/6d5464b4-acf0-11e5-91bf-8ac8b1c271f6.jpg)
![chicken-fajitas-a-3](https://cloud.githubusercontent.com/assets/16444512/12011656/6d548142-acf0-11e5-93ff-d78aa33fb6be.jpg)
![chicken-fajitas-a-5](https://cloud.githubusercontent.com/assets/16444512/12011654/6d53ff6a-acf0-11e5-909d-3dbf6c5d50e9.jpg)
![chicken-fajitas-a-8](https://cloud.githubusercontent.com/assets/16444512/12011658/6d6b6a6a-acf0-11e5-91fc-f3d37255cea4.jpg)
![chicken-fajitas-a-10](https://cloud.githubusercontent.com/assets/16444512/12011659/6d6bce2e-acf0-11e5-985f-65404e421176.jpg)
![slicing-chicken-fajitas](https://cloud.githubusercontent.com/assets/16444512/12011660/6d6f1de0-acf0-11e5-86c2-1633849497b1.jpg)

**Comment by ooduhastoo** [comment]
![111111111111111111111111111](https://cloud.githubusercontent.com/assets/16444512/12011686/83315354-acf1-11e5-8183-7a5c581f856b.jpg)

**Comment by AngryGantz** [comment]
Отписался в скайпе, но повторюсь тут на всякий.  Вроде поборол проблему виндузятного хрома с добавлением  фото. Эмуляция норм. Проверяйте. Заодно вроде бы нарвался на момент, из-за которого у вас могла ошибка при отправки вылезти. Связано с последним добавлением дополнительных маркеров в форму, которые отдельностоящие. Если ни один не был выбран из них это вызывало крэш процесса. Исправил соответственно.
