### ISSUE TITLE
"Не срочно" Небольшое исправление

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#50]
Замените пожалуйста калории на время подготовки 
![default](https://cloud.githubusercontent.com/assets/16444512/12011756/a20a1eac-acf4-11e5-8a7e-9c37d4b88962.jpg)

**Comment by AngryGantz** [comment]
Так есть же время готовки уже...

**Comment by ooduhastoo** [comment]
Просто как выяснилось калории  вообще не к чему  а время подготовки ... Например Замариновали шашлык на 8  часов а приготовили за 20 мин ..  Логично ... Время подготовки 8 часов  приготовление 20 мин...   Кстати калории в материале не выводятся

**Comment by AngryGantz** [comment]
Оставляем так? Рекомендую пока оставить.
