### ISSUE TITLE
"Не срочно" Строка внизу сайта

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#51]
Нахожусь не в админке и вообще гость на сайте вижу :
![7777777777777777777777](https://cloud.githubusercontent.com/assets/16444512/12012351/90f241e8-ad09-11e5-8cff-408574b1135b.jpg)

**Comment by AngryGantz** [comment]
Сайт в режиме отладки. Это не боевой режим. Я пойму когда пора переводить
