### ISSUE TITLE
"Не срочно" title 

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#54]
форма title для маркеров и рецептов

**Comment by AngryGantz** [comment]
Сделано

**Comment by AngryGantz** [comment]
Что-то не так?

**Comment by ooduhastoo** [comment]
Группы маркеров "Title" если возможно

**Comment by AngryGantz** [comment]
Мммм....   Рецепты то все равно по одному маркеру потом выходят. Какую логику то применять, когда титл группы выводить?
