### ISSUE TITLE
"Не срочно" Нет такой страницы

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#55]
Нет такой страницы. Вышибает ошибку
![01](https://cloud.githubusercontent.com/assets/16444512/12051179/0d3affa4-af19-11e5-847c-82888e40aea7.jpg)

**Comment by AngryGantz** [comment]
Чего хотим?

**Comment by ooduhastoo** [comment]
Что бы на сайте в области контента была картинка и написано "Такая страница не найдена" например

**Comment by AngryGantz** [comment]
ааа. ок. Чуть позже, пусть повисит.

**Comment by ooduhastoo** [comment]
Страница которую Вы ищете отсутствует ;( Попробуйте посмотреть в других разделах сайта.
![404](https://cloud.githubusercontent.com/assets/16444512/12118474/222a43a4-b3e0-11e5-9703-a22f611c62b4.png)

Как то так

**Comment by AngryGantz** [comment]
сделал надпись в контенте просто...  Уверены что эту тетку надо?

**Comment by ooduhastoo** [comment]
Не уверен)

**Comment by AngryGantz** [comment]
вот и я не уверен...
