### ISSUE TITLE
"Не срочно" Настройка рекламного блока 

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#57]
Настройка рекламного блока  right1  ... Что бы корректно отображался на разных видах устройства

**Comment by AngryGantz** [comment]
а что не так?

**Comment by ooduhastoo** [comment]
не могу сообразить как его поправить для корректного отображения на разных устройствах

**Comment by AngryGantz** [comment]
медиа в блоке наверное, но это вроде на вас -))) Ежели что, позже помогу.
