### ISSUE TITLE
"Не срочно" Добавить позицию рекламного блока

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#58]
Добавьте пожалуйста позицию рекламного блока. Размеры на усмотрение по ширине блока контента
![xxx](https://cloud.githubusercontent.com/assets/16444512/12053399/215e89a6-af32-11e5-9ec4-730ace1c1912.jpg)

**Comment by AngryGantz** [comment]
Сделано. Место посадки в управлении рекламными блоками - "recipie_step" (кстати, можно добавлять по несколько штук на 1 место посадки, будет вылетать рандомный блок для этого места посадки)

**Comment by ooduhastoo** [comment]
Спасибо
