### ISSUE TITLE
"не срочно" Вход на сайт 

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#6]
Войти через  ВК ОК ФБ ..  Апи   я предоставлю
![6](https://cloud.githubusercontent.com/assets/16444512/12006705/efea53e4-abfa-11e5-86ec-b57cfe013ebb.jpg)

**Comment by ooduhastoo** [comment]
Если сложно реализовать делаем отбой и убираем их

**Comment by AngryGantz** [comment]
Пока кнопки выключу, а тикет оставляйте. Пусть висит, он хлеба не просит.

**Comment by AngryGantz** [comment]
кнопки пока убрал
