### ISSUE TITLE
"Не срочно" Подписаться на новости

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#60]
![111](https://cloud.githubusercontent.com/assets/16444512/12054653/b92e186c-af3e-11e5-8a00-b323c4c96823.jpg)

**Comment by AngryGantz** [comment]
Проверьте сейчас. у меня всё норм.

**Comment by ooduhastoo** [comment]
Проверю как только рецепты смогу добавлять)

**Comment by AngryGantz** [comment]
ммм... проверили?

**Comment by ooduhastoo** [comment]
Не приходят оповещения о новостях
