### ISSUE TITLE
"Срочно" Что это ???)

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#61]
Косяк при добавлении рецепта !!! )
![1](https://cloud.githubusercontent.com/assets/16444512/12055999/da2e7478-af4b-11e5-8f2d-24788b5eaf61.jpg)

**Comment by AngryGantz** [comment]
Полностью перепахал всю систему загрузки и именования изображений на сайт. Теперь картинки грузятся под своими именами, в папки по 1 папке на 1 день. именование папок по дате год-месяц-день. Могу добавить час, минуту и секунду -))) Но это уже перебор в файловом дереве будет.   Откуда дубли так и не понял. Но так много всего поменялось, возможно глюк где-то был исправлен по дороге. По крайней мере я загрузил несколько тестовых постов, дубли не вылезли. (кстати, это была не замена картинок, а добавление нескольких шагов из страых постов к новым)   Вроде сейчас нет, но я эту проблему не устранял, ибо не поянл толком откуда ноги росли. Могла быть пофиксена по дороге, могла не быть. Надо тестировать.

**Comment by ooduhastoo** [comment]
Спасибо

**Comment by ooduhastoo** [comment]
Добавил рецепт зашел за админа вот что я вижу ( Опять глюк
![000](https://cloud.githubusercontent.com/assets/16444512/12071003/e4dc2d08-b0ad-11e5-8405-582033e92c52.jpg)
