### ISSUE TITLE
"Не срочно" Путаница с маркерами

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#64]
Хотелось бы что бы если это блюдо принадлежало напиткам выводилось слово напитки:(Маркер)Алкогольные, если выпечка выпечка:блины ... Получается что выводилась группа маркеров к которой принадлежит рецепт
![01](https://cloud.githubusercontent.com/assets/16444512/12070524/e9741fe4-b092-11e5-870b-e97652a930ee.jpg)

**Comment by AngryGantz** [comment]
Там выводился маркер из группы Блюдо. Вы эту группу преобразовали в "наши рецепты" могу туда вывести любую другую группу, будет выводиться маркер из этой группы, к которой приписан рецепт. Если проверять есть ли вообще маркер у рецепта в этой группе и если нет, то переходить к другой,  и выводить группу только если есть маркер у рецепта из этой группы, начнут вылезать опять таки всякие меню, спец группы и т.д. Подумайте над тем, что-бы выводить там всетаки конкретную группу. Она может быть служебной, то есть больше нигде не проявляться. Вопрос в том, что вы ходите там выводить, какую информацию....
