### ISSUE TITLE
Стекло таблицы

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#88]
Дружит ли шаблон с таблицами и как это реализовать ??

Например карточка товаров  

3 примера  
 таблица

Список комплектации цена
Список комплектации цена
Список комплектации цена

**Comment by AngryGantz** [comment]
Нарисовать нужную табличку например в ворде и вставить в админке кнопкой "Вставить из ворд" в описание товара. Долдно быть нормально, хотя не проверял именно таблички.
