### ISSUE TITLE
Стекло карточка товаров

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#90]
p ?   откуда-то параграфы  нормально ли это ??  Текст был пропущен через блокнот
![1](https://cloud.githubusercontent.com/assets/16444512/12848479/a2da99fc-cc33-11e5-90f1-dee67564368e.jpg)

**Comment by AngryGantz** [comment]
Если в блокноте был разрыв строк редактор создает параграфы на этом месте. Это нормально.
