### ISSUE TITLE
Стекло Тел номера

### ISSUE THREAD

**Issue by ooduhastoo** [AngryGantz/cms-cookbook#93]
Заказчик просил указать эти тел номера на сайте  

 `<a href="tel:+79194114589"> +7(919)411-45-89</a>
<a href="tel:+79166031765"> +7(495)775-26-13</a>`

**Comment by ooduhastoo** [comment]
Еще на мобильнике в шапки нету контактов

**Comment by ooduhastoo** [comment]
Еще бы из админки сделать что бы можно было контакты менять почту тел номера

**Comment by AngryGantz** [comment]
Fixed. В Админке "Общие настройки". 
В мобильном варианте в шапке контакты не предусмотрены. Воткнул в меню. Вроде неплохо.
